- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationStoreClient.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationUtils.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/BearerTokenReactiveAuthenticationManagerResolver.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/CookieSerializer.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/JitProvisioningAuthenticationSuccessHandler.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/JwtAuthenticationLogoutHandler.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/JwtAuthenticationProcessor.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/LogoutAllServerLogoutHandler.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/OidcAuthenticationProcessor.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/OrganizationWebFilter.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/AuthenticationUtilsTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/BearerTokenReactiveAuthenticationManagerResolverTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/CookieSerializerTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/CookieServerAuthorizationRequestRepositoryTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/CookieServerOAuth2AuthorizedClientRepositoryTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/CookieServerRequestCacheTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/CookieServerSecurityContextRepositoryTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/JitProvisioningAuthenticationSuccessHandlerTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/JwtAuthenticationProcessorTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/OidcAuthenticationProcessorTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/OrganizationWebFilterTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/ReactiveCookieServiceTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/TestUtils.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/UserContextWebFluxTest.kt
> feat: switch AuthenticationStoreClient from coroutines to reactor

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AppLoginWebFilter.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/CookieSerializer.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/CookieServerAuthorizationRequestRepository.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/CookieServerOAuth2AuthorizedClientRepository.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/CookieServerRequestCache.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/CookieServerSecurityContextRepository.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/DelegatingServerRequestCache.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/ReactiveCookieService.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/CookieSerializerTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/CookieServerAuthorizationRequestRepositoryTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/CookieServerOAuth2AuthorizedClientRepositoryTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/CookieServerRequestCacheTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/CookieServerSecurityContextRepositoryTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/ReactiveCookieServiceTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/TestUtils.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/UserContextWebFluxTest.kt
> fix: make CookieSerializer::readCookieSecurityProperties reactive and non-blocking

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationUtils.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/AuthenticationUtilsTest.kt
> feat: Parse OAuth2 token list attr in more general manner

- gradle/scripts/detekt-config.yml
- gradle/wrapper/gradle-wrapper.properties
Also fix detekt configuration.
> feat: use gradle 8.8

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/Auth0LogoutHandler.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/CognitoLogoutHandler.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/JwtAuthenticationLogoutHandler.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/QueryParamOidcClientInitiatedServerLogoutSuccessHandler.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/ServerOAuth2AutoConfiguration.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/UriExtensions.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/UriExtensionsTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/UserContextWebFluxTest.kt
> feat: allow to define logout URL in query parameter

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/Auth0LogoutHandler.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/CognitoLogoutHandler.kt
Wrap call for returnTo query param to only create URI if not null.
JIRA: STL-631
risk: low
> fix: NRE in auth0/cognito login

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/OrganizationCorsConfigurationSource.kt
> feat(cors): expose Content-Disposition header

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/CustomOAuth2Validator.kt
> feat: Do not use typ header for JWT validation

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationStoreClient.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/ServerOAuth2AutoConfiguration.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/oauth2/client/CustomAttrsAwareOauth2AuthorizationRequestResolver.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/oauth2/client/CustomAttrsAwareOauth2AuthorizationRequestResolverTest.kt
> feat: Apply custom auth attributes on authentication call

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationUtils.kt
Previously, if the metadata was missing an endpoint definition, we would get a null pointer exception when trying to call `toASCIIString()` on the null uri. Enhanced the logic to handle this case and added `missingEndpoints` as part of the `MetadataValidationResult` to be used when providing error message details.
risk: low
> fix: handle missing endpoints for azureb2c

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationUtils.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/AuthenticationUtilsTest.kt
In order to get an access token, must provide the clientID as a scope for azure B2C
JIRA: LX-650
risk: low
> fix: proper azure b2c provider scope

- .github/workflows/pre-merge.yml
- renovate.json5
older v3 will stop working soon
risk: nonprod
JIRA: INFRA-3870
> ci: upgrade upload-artifact action to v4

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationStoreClient.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationUtils.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/HostBasedReactiveClientRegistrationRepository.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/JitProvisioningAuthenticationSuccessHandler.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/ServerOAuth2AutoConfiguration.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/AuthenticationUtilsTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/HostBasedReactiveClientRegistrationRepositoryTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/JitProvisioningAuthenticationSuccessHandlerTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/TestUtils.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/UserContextWebFluxTest.kt
> feat: Add support for JIT defined via Organization setting

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationStoreClient.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/JitProvisioningAuthenticationSuccessHandler.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/JitProvisioningAuthenticationSuccessHandlerTest.kt
> feat: Allow custom userGroups claim name for JIT

- .sonar.settings
risk: nonprod
JIRA: INFRA-3673
> chore: use jdk17 for sonar scan

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationStoreClient.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationUtils.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/JitProvisioningAuthenticationSuccessHandler.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/AuthenticationUtilsTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/JitProvisioningAuthenticationSuccessHandlerTest.kt
> feat: Remove JIT enablement via Organization entity

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationAuditClient.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/BearerTokenReactiveAuthenticationManagerResolver.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/CustomReactiveOAuth2UserService.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/DelegatingServerLogoutSuccessHandler.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/LoggerUtil.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/LoggingRedirectServerAuthenticationSuccessHandler.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/ReactiveCommunicationClientsConfiguration.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/ServerOAuth2AutoConfiguration.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/ServerOAuth2FailureHandler.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/BearerTokenReactiveAuthenticationManagerResolverTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/OAuth2UserValidatorTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/ServerOAuth2AutoConfigurationTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/ServerOAuth2FailureHandlerTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/UserContextWebFluxTest.kt
Added new interface for AuthenticationAuditClient, which provides functions to record successful login, failed login, and logout events with information which will be used in implementation to publish to audit logs.
JIRA: LX-858
risk: high
> feat: audit logging service

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
Use customized gdc-gradle with configured repos.
> fix: switch publishing to codeartifact

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationProcessor.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationStoreClient.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationUtils.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/OidcAuthenticationProcessor.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/ServerOAuth2AutoConfiguration.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/UserContextHolder.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/AuthenticationUtilsTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/JwtAuthenticationProcessorTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/OidcAuthenticationProcessorTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/UserContextAuthenticationProcessorTest.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/UserContextWebFluxTest.kt
It allows to propagate the token down to databases. Some databases, e.g. Snowflake, can be integrated with Oauth providers.
JIRA: GDAI-137
risk: high
> feat(oauth): Pass Oauth access token to microservices

- .github/workflows/post-merge.yml
- .github/workflows/pre-merge.yml
> config: init codeArtifact token for gradle build

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/OidcAuthenticationProcessor.kt
Mono.zip must not provide empty result if the accessToken part is empty.
jira: GDAI-137
risk: low
> fix(oauth): handle empty accessToken properly

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/BearerTokenReactiveAuthenticationManagerResolver.kt
The flow was not setup properly previously, so the audit logging was not actually happening.
JIRA: LX-1015
risk: low
> fix: JWT login success audit logging

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/CookieServerRequestCache.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/CookieServerRequestCacheTest.kt
Do not invalidate SPRING_REDIRECT_URI cookie on UNAUTHORIZED request.
JIRA: LX-1022
risk: high
> fix: Fix SPRING_REDIRECT_URI cookie invalidation

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/JitProvisioningAuthenticationSuccessHandler.kt
Do not provision user userGroups, when userGroups claim is present, but the userGroups provisioning is disabled in jitSettings
JIRA: trivial
risk: low
> fix: Fix JIT userGroups provisioning

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationUtils.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/JwkCachingReactiveDecoderFactory.kt
> chore(logging): include sub claim in the expired JWT exception

- gradle/wrapper/gradle-wrapper.properties
> chore: use new s3 bucket

- gooddata-server-oauth2-autoconfigure/src/main/kotlin/AuthenticationStoreClient.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/BearerTokenReactiveAuthenticationManagerResolver.kt
- gooddata-server-oauth2-autoconfigure/src/main/kotlin/JwtAuthenticationProcessor.kt
- gooddata-server-oauth2-autoconfigure/src/test/kotlin/JwtAuthenticationProcessorTest.kt
Fixing the initial implementation of the JWT jit implementation
- creating the user with the user id specified by the token
> fix: Fix JWT JIT implementation
